# rss_feeds.py

rss_feeds = {
    "IGN": "http://feeds.ign.com/ign/all",
    "PC Gamer": "https://www.pcgamer.com/rss/",
    "Kotaku": "https://kotaku.com/rss",
    "ESPN Top Headlines": "http://www.espn.com/espn/rss/news",
    "BBC Sport Top Stories": "http://feeds.bbci.co.uk/sport/rss.xml?edition=int",
    "Yahoo Sports Top News": "https://sports.yahoo.com/rss/",
    "Sports Illustrated Top Stories": "https://www.si.com/rss/si_top_stories.rss",
    "CBS Sports Top Headlines": "https://www.cbssports.com/rss/headlines",
    "NBC Sports Top Stories": "https://profootballtalk.nbcsports.com/feed/",
    "BBC World News": "http://feeds.bbci.co.uk/news/world/rss.xml",
    "CNN World News": "http://rss.cnn.com/rss/edition_world.rss",
    "The New York Times - World News": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "Al Jazeera English": "https://www.aljazeera.com/xml/rss/all.xml",
    "The Guardian - World News": "https://www.theguardian.com/world/rss",
    "Reuters - World News": "http://feeds.reuters.com/Reuters/worldNews",
    "NPR World News": "https://feeds.npr.org/1004/rss.xml",
    "TechCrunch": "http://feeds.feedburner.com/TechCrunch/",
    "The Verge": "https://www.theverge.com/rss/index.xml",
    "Ars Technica": "http://feeds.arstechnica.com/arstechnica/index",
    "CNET Top Stories": "https://www.cnet.com/rss/news/",
    "Wired Top Stories": "https://www.wired.com/feed/rss",
    "Engadget": "https://www.engadget.com/rss.xml",
    "Bleeping Computer": "https://www.bleepingcomputer.com/feed/",
    "Krebs on Security": "https://krebsonsecurity.com/feed/",
    "The Hacker News": "https://feeds.feedburner.com/TheHackersNews",
    "Dark Reading": "http://www.darkreading.com/rss_simple.asp",
    "Naked Security by Sophos": "https://nakedsecurity.sophos.com/feed/",
}
